### ISSUE TITLE
what is the design principle of QR in the controller?Do you have any information about it?

### ISSUE THREAD

**Issue by Faust-Wang** [eyler94/EE674LQR#1]

**Comment by eyler94** [comment]
Sorry, I am not quite sure what you are asking.

If you are wondering where the QR controller is implemented, it can be found in the following directory and file:
https://github.com/eyler94/EE674LQR/blob/master/chap6LQR/lqr_control.py

If you are looking for more information about LQR controllers, I would recommend Wikipedia https://en.wikipedia.org/wiki/Linear%E2%80%93quadratic_regulator

or the text book I used when I learned about it:
https://www.amazon.com/gp/product/0691140219/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 

This doesn't seem to call attention to any problem with my code though, so I will be closing this issue.

Thanks.

**Comment by Faust-Wang** [comment]
I would like to ask about the meaning of some of the matrix construction in your code, such as Alonaug T, Cr (what does it mean and why is it negative), Alon Aug, Blon AUG, etc. And most importantly, there is no pe state in the horizontal state, so can't this controller control the pe state？
I want to know the source of your controller design and not the theory of LQR.
Thank you.
